name: "MQTT Staging Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
    paths-ignore:
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/mqtt/Dockerfile
          push: true
          tags: asia-southeast1-docker.pkg.dev/scamo-group/xkamail/huberlink-mqtt:latest
    outputs:
      image: asia-southeast1-docker.pkg.dev/scamo-group/xkamail/huberlink-mqtt@${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: deploys-app/deploys-action@v1
        with:
          project: ezpay-staging
          location: gke.cluster-rcf2
          name: huberlink-mqtt
          image: ${{ needs.build.outputs.image }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}